# Generated by Django 6.0.6 on 2026-06-05 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=1)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='vocabulary.level')),
            ],
            options={
                'ordering': ['level__name', 'order', 'title'],
                'unique_together': {('level', 'order')},
            },
        ),
        migrations.CreateModel(
            name='VocabularyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uzbek_word', models.CharField(max_length=120)),
                ('english_word', models.CharField(max_length=120)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='vocabulary.unit')),
            ],
            options={
                'ordering': ['uzbek_word'],
                'unique_together': {('unit', 'uzbek_word', 'english_word')},
            },
        ),
    ]
