# Generated by Django 6.0.6 on 2026-06-06 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vocabularyword',
            unique_together={('unit', 'uzbek_word')},
        ),
    ]
