# Generated by Codex on 2026-06-06

from django.db import migrations, models


DEFAULT_EVENTS = [
    ('correct_match', 'Correct!', 'Nice match.'),
    ('incorrect_match', 'Try Again', 'Those words do not match.'),
    ('life_lost', 'Life Lost', 'Be careful. Your lives carry across rounds.'),
    ('no_lives_remaining', 'Game Over', 'You have no lives remaining.'),
    ('round_completed', 'Round Complete!', 'Great job! Get ready for the next round.'),
    ('round_failed', 'Round Failed', 'Retry this round when you are ready.'),
    ('timer_expired', 'Time Is Up', 'The round timer expired.'),
    ('unit_completed', 'Congratulations!', 'You completed the unit.'),
    ('continue_game', 'Continue', 'You bought one life and can keep playing.'),
]


def create_default_events(apps, schema_editor):
    GameEventAsset = apps.get_model('vocabulary', 'GameEventAsset')
    for event_type, title, message in DEFAULT_EVENTS:
        GameEventAsset.objects.get_or_create(
            event_type=event_type,
            defaults={
                'title': title,
                'message': message,
                'active': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_alter_vocabularyword_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameEventAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('correct_match', 'Correct match'), ('incorrect_match', 'Incorrect match'), ('life_lost', 'Life lost'), ('no_lives_remaining', 'No lives remaining'), ('round_completed', 'Round completed'), ('round_failed', 'Round failed'), ('timer_expired', 'Timer expired'), ('unit_completed', 'Unit completed'), ('continue_game', 'Continue game')], max_length=40, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField(blank=True)),
                ('sound_file', models.FileField(blank=True, upload_to='game_events/sounds/')),
                ('gif_file', models.FileField(blank=True, upload_to='game_events/gifs/')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['event_type'],
            },
        ),
        migrations.RunPython(create_default_events, migrations.RunPython.noop),
    ]
